language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - pip install --upgrade setuptools
  - pip install .
  - pip install --editable .[dev]
  - py.test ./tests -s -vv
